### ISSUE TITLE
Crash: "Could not execute entrypoint stage 'main' due to errors, provided by 'smoothskies'!"

### ISSUE THREAD

**Issue by HatTrkPatrk** [MicrocontrollersDev/Smooth-Skies#1]
With Smooth Skies mod obtained from ModRinth, running on Fabric 1.20.1 (loader version 0.15.7). Encountering the crash message in the title (game does not load and crashes to desktop). Here's the information in the crash-reports text file:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'smoothskies'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: dev/isxander/yacl3/config/v2/api/ConfigClassHandler
	at dev.microcontrollers.smoothskies.config.SmoothConfig.<clinit>(SmoothConfig.java:16)
	at dev.microcontrollers.smoothskies.SmoothSkies.onInitialize(SmoothSkies.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: dev.isxander.yacl3.config.v2.api.ConfigClassHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 9 more
```

This crash occurs even on a game setup with nothing but Smooth Skies, YACL, and the Fabric API.

![image](https://github.com/MicrocontrollersDev/Smooth-Skies/assets/5185596/449a81d7-3867-4bc2-9f87-ac65080e7db2)

Let me know if I can provide any further info. Thanks!

**Comment by MicrocontrollersDev** [comment]
All good!
